#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)


sleep 10s

export DISPLAY=:0.0
xinput set-prop 'ILITEK Multi-Touch-V5000' 'Coordinate Transformation Matrix' 0 -1 1 1 0 0 0 0 1

# invoke global X session script
. /etc/X11/Xsession


